### ISSUE TITLE
mock-1.0.1, how to proceed?

### ISSUE THREAD

**Issue by nicoddemus** [conda-forge/mock-feedstock#5]
Hi,

For internal reasons at my company we need `mock` version `1.0.1`, but conda-forge only has versions >= `1.3.0`.

I'm wondering how to proceed, should I go to the usual route and open a PR? The only issue I see is that after merging `master` would contain a recipe for version `1.0.1` instead of the latest one (`2.0.0`). That could be fixed by reverting the commit though.

cc @gqmelo

**Comment by jakirkham** [comment]
Two options on this one.

1. Do the typical PR and we revert the change (as you have mentioned).
2. Create a branch for this version and add the PR to that branch.

2 is the more principled route and is used when we need to maintain an old version (maybe this case?). 1 is a hacky unprincipled route, but has its benefits.

My preference is towards 2. However, if no maintenance will occur 1 could be fine. What do you think?

**Comment by nicoddemus** [comment]
> Create a branch for this version and add the PR to that branch.

Hmm could you clarify what you mean? Please note I'm not a maintainer on this repository so I can't create branches on it.

**Comment by jakirkham** [comment]
Right, in this case, I would add the branch and then you would PR against it (or redirect an existing PR against it).

**Comment by nicoddemus** [comment]
I see, thanks. Could you create the branch then?

**Comment by ocefpaf** [comment]
> I see, thanks. Could you create the branch then?

Just bumped in this issue. I believe you already worked around it but if you still need a `v1.x` branch let me know and I'll create it for you @nicoddemus.

**Comment by nicoddemus** [comment]
Thanks @ocefpaf, we already have a workaround in place. 😁
